#!/bin/bash
set -ux

AUTHORIZED_CARDS=${AUTHORIZED_CARDS:-card_ids.txt}

CARD_ID=${1:-}

# Fail early on invalid format
if ! [[ $CARD_ID =~ ^0x[a-fA-F0-9]+$ ]]; then
  echo 'Invalid card id'
  exit 1
fi

# The card is authorized if grep exits cleanly
grep --max-count=1 --extended-regexp "^${CARD_ID}\$" $AUTHORIZED_CARDS

if [ $? -gt 0 ]; then
  echo "Card is not authorized: $CARD_ID"
  exit 2
fi

