#!/bin/bash
set -eu

if [ ${DEBUG:-0} -eq 1 ]; then
  set -x
fi

# Pins are numbered after the wiringPi scheme (https://pinout.xyz/pinout/wiringpi)
GPIO_PIN_DOOR=${GPIO_PIN_DOOR:-17}
STAY_UNLOCKED_SEC=${STAY_UNLOCKED_SEC:-2}

STATE_UNLOCKED=dh
STATE_LOCKED=dl

# This function will always be invoked on script exit
function cleanup {
  # Lock the door
  raspi-gpio set $GPIO_PIN_DOOR $STATE_LOCKED
  echo "Door locked"
}
trap cleanup EXIT

# Unlock the door
raspi-gpio set $GPIO_PIN_DOOR op
raspi-gpio set $GPIO_PIN_DOOR $STATE_UNLOCKED
echo "Door unlocked"
sleep $STAY_UNLOCKED_SEC
